theme: minima
title: My Coding Blog

author: Katy Overstreet
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will show my journey as I learn how to program.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  katyoverstreet # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage



